#!/usr/bin/env bash
#
# Concatenates the migrations into a single supabase-setup.sql that can be
# pasted into the Supabase SQL editor in one go.
#
# The output is generated, not checked in: a second copy of the schema would
# drift from supabase/migrations/ the moment one of them changed.
#
#   ./scripts/build-setup-sql.sh            # writes ./supabase-setup.sql
#   ./scripts/build-setup-sql.sh out.sql    # writes out.sql
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/supabase-setup.sql}"

{
  cat <<'HEADER'
-- ============================================================================
--  LinkedIn Lead Finder — complete database setup
--
--  Paste this whole file into the Supabase SQL editor and press Run. It is the
--  files in supabase/migrations/ concatenated in order, so running this once is
--  equivalent to running them one by one.
--
--  Safe on a fresh project. Running it twice will error on the CREATE TYPE and
--  CREATE TABLE statements — expected; it is not idempotent.
--
--  Generated by scripts/build-setup-sql.sh — do not edit by hand.
-- ============================================================================
HEADER

  for file in "$ROOT"/supabase/migrations/*.sql; do
    printf '\n-- ###########################################################################\n'
    printf -- '-- #  %s\n' "$(basename "$file")"
    printf -- '-- ###########################################################################\n\n'
    cat "$file"
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
